name: students_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  image_picker: ^0.8.7+5
  path_provider: ^2.0.15
  photo_view: ^0.14.0
  salomon_bottom_bar: ^3.3.2
  

dev_dependencies:
  build_runner: ^2.1.5

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1

flutter:
, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/studentImage.png
    - assets/images/download.png
    - assets/avatar.jpg
    - assets/images/registration_background.png
  